# Generated by Django 5.0.1 on 2025-10-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateForecaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=10)),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_file', models.FileField(upload_to='ml_models/climate_forecasting/')),
            ],
            options={
                'verbose_name': 'Climate Forecasting Model',
                'verbose_name_plural': 'Climate Forecasting Models',
            },
        ),
        migrations.CreateModel(
            name='CropRecommender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=10)),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_file', models.FileField(upload_to='ml_models/crop_recommendation/')),
            ],
            options={
                'verbose_name': 'Crop Recommendation Model',
                'verbose_name_plural': 'Crop Recommendation Models',
            },
        ),
        migrations.CreateModel(
            name='DiseaseDetector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=10)),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_file', models.FileField(upload_to='ml_models/disease_detection/')),
            ],
            options={
                'verbose_name': 'Disease Detection Model',
                'verbose_name_plural': 'Disease Detection Models',
            },
        ),
    ]
