# Generated by Django 5.0.1 on 2025-10-07 19:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('temperature', models.DecimalField(decimal_places=2, help_text='Temperature in Celsius', max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, help_text='Humidity percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rainfall', models.DecimalField(decimal_places=2, help_text='Rainfall in mm', max_digits=6)),
                ('wind_speed', models.DecimalField(decimal_places=2, help_text='Wind speed in km/h', max_digits=5)),
                ('pressure', models.DecimalField(decimal_places=2, help_text='Pressure in hPa', max_digits=7)),
                ('description', models.CharField(max_length=200)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Weather Data',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(choices=[('cereals', 'Cereals'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('legumes', 'Legumes'), ('tubers', 'Tubers')], max_length=20)),
                ('variety', models.CharField(blank=True, max_length=100)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('area_planted', models.DecimalField(decimal_places=2, help_text='Area in acres', max_digits=10)),
                ('status', models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('harvested', 'Harvested'), ('failed', 'Failed')], default='planted', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-planting_date'],
            },
        ),
        migrations.CreateModel(
            name='GreenPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('intercropping', 'Intercropping'), ('organic', 'Organic Farming'), ('recycling', 'Recycling'), ('water_conservation', 'Water Conservation'), ('composting', 'Composting'), ('renewable_energy', 'Renewable Energy')], max_length=30)),
                ('description', models.TextField()),
                ('points_earned', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='green_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(max_length=200)),
                ('farm_size', models.DecimalField(decimal_places=2, help_text='Farm size in acres', max_digits=10)),
                ('total_green_points', models.IntegerField(default=0)),
                ('badge_tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
